### ISSUE TITLE
Scenes and images don't get loaded into UI

### ISSUE THREAD

**Issue by monajalal** [pderoovere/dimo-labeling#5]
I have 4 test images in a test_data folder and created a models folder inside it with the models_info.json

![image](https://github.com/pderoovere/dimo-labeling/assets/1892917/e3a4f361-c40a-490f-aaac-87200513f642)

and

![image](https://github.com/pderoovere/dimo-labeling/assets/1892917/454cd071-993f-4a4c-9162-31bcb2cfef4b)

I have 

```
(base) mona@ada:~/dimo-labeling/test_data$ tree .
.
├── 000000
│   └── rgb
│       ├── 000000.png
│       ├── 000001.png
│       ├── 000002.png
│       └── 000003.png
└── models
    ├── models_info.json
    └── obj_000001.ply

3 directories, 6 files


```

![image](https://github.com/pderoovere/dimo-labeling/assets/1892917/c38f10f7-4dea-4e2b-8849-5e42cc6df970)

as you see no images get loaded or no Scenes. 

![Screenshot from 2024-03-25 14-34-05](https://github.com/pderoovere/dimo-labeling/assets/1892917/74586a0d-3e48-4813-85cc-26c2ece8a602)

I tried to follow `Sim-to-Real Dataset of Industrial Metal Objects` paper structure for data.

```
(dimo-labeling) mona@ada:~/dimo-labeling/frontend$ ng version
Workspace extension with invalid name (defaultProject) found.

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.2
Node: 20.9.0
Package Manager: npm 10.1.0
OS: linux x64

Angular: 17.3.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@angular/cli                    17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
    

```

**Comment by pderoovere** [comment]
Hi @monajalal,

Thanks for trying out the labeling tool!

The stacktrace states `FileNotFoundError: [Errno 2] No such file or directory '../test_data/models/models_info.json'.`
However, looking at the output of your `tree` command, the file should to exist.
But looking at the folder structure, you are missing a "camera" folder. Scenes (`000000`) should be inside of this folder. 

Also, pass `--models_dir` and `--images_dir` arguments when starting the backend, e.g. `python api.py --path ../test_data --models_dir models --images_dir real_camera`.

Does this solve the issue?
