### ISSUE TITLE
Some bugs in current UI

### ISSUE THREAD

**Issue by gachiemchiep** [pderoovere/dimo-labeling#7]
Hello @pderoovere 

For current version, there're few bugs in the UI that make this tool unusable.

1. delete button is missing from UI
![image](https://github.com/pderoovere/dimo-labeling/assets/2300329/a36f34be-6a23-4164-9b0d-13bf158e6724)

![image](https://github.com/pderoovere/dimo-labeling/assets/2300329/7ed5e767-3508-4f54-a9ab-85d01b55a5aa)

2. save button has wrong action

For now instead of saving only current image and annotation. 
It will write current annotation to all available images.

![image](https://github.com/pderoovere/dimo-labeling/assets/2300329/ee210f0a-0f80-47a7-bb69-710574f8f926)

Would you mind take a look at these. 
If you don't have time, please point me the method definition. 
I think I can fix it.

Best regards.
truong

**Comment by pderoovere** [comment]
Hi @gachiemchiep

Thanks for your feedback!
1. Fixed
2. Clicking "Save" should save the annotations of all scenes. This way users do not have to think about saving each scene individually. Multiple scenes can be annotated and saved at once. However, annotations of the active scene should **not** be stored for all scenes. I cannot reproduce this, can you share an example dataset?
