### ISSUE TITLE
creating the symmetries_continous and symmetries_discete fields for models_info.json file

### ISSUE THREAD

**Issue by monajalal** [pderoovere/dimo-labeling#8]
Hi Peter

Could you please share how to create the symmetries_continous and symmetries_discrete for a model for models_info.json?

![image](https://github.com/pderoovere/dimo-labeling/assets/1892917/8819bed0-725a-485c-81f6-5182baf99fe3)

Do you run a piece of code to retrieve these numbers?

**Comment by pderoovere** [comment]
Hi @monajalal, for DIMO, I created them manually based on the [BOP format](https://bop.felk.cvut.cz/home/).
There are [HALCON scripts](https://github.com/thodan/bop_toolkit/issues/50#issuecomment-903632625) for generating them automatically, but I haven't tried it myself.
